### ISSUE TITLE
RfcObject <MySapInterface>

### ISSUE THREAD

**Issue by don-hue** [grupoboticario/nestjs-sap-rfc#664]
```
public async test(): **MySapInterface** {
    return this.sapService.execute<**MySapInterface**>('rfcName', {
      ...rfcParams,
    });
  }
```

can someone tell me what  **MySapInterface** looks like ? (How does the Data Structure look like ?) 

According to VsCode, there should be a RfcObject, but it is not defined in the Readme file. 

BTW, ` npm run doc` does not work. Script for npm run doc is also not shown in package.json file.

**Comment by alvarolimajr** [comment]
Hi @don-hue, how are you?
I am going to update the README.md.
You are correct, the structure is an `RfcObject`, but we export these named structures, here's an example:

```ts
import {
  InjectSapService,
  SapService,
  SapRfcObject,
  SapRfcStructure,
} from 'nestjs-sap-rfc';
import { Inject } from '@nestjs/common';

// RfcStructure
type PositionData = SapRfcStructure; // SAP structure

// RfcStructure
interface NestedData extends SapRfcStructure {
    readonly E_NESTED?: string; // SAP field name
}

// MySapInterface
interface MySapInterface extends SapRfcObject {
  readonly E_NAME?: string; // SAP field name
  readonly E_DATA?: PositionData; // SAP field name
  readonly E_DATA2?: NestedData; // SAP field name
  readonly E_ERROR?: string; // SAP field name
  readonly I_OBJID?: string; // SAP field name
}

@Injectable()
export class MyService {
  /**
   * @param {SapService} sapService
   */
  constructor(
    @Inject('service_name')
    private readonly sapService: SapService,
  ) {}

  public async test(): MySapInterface {
    return this.sapService.execute<MySapInterface>('rfcName', {
      ...rfcParams,
    });
  }
}
```

**Comment by alvarolimajr** [comment]
@don-hue the npm run doc is working, I just ran it here.
![image](https://user-images.githubusercontent.com/74659215/223428330-765d5a55-62b9-492a-8308-264170003a00.png)
![image](https://user-images.githubusercontent.com/74659215/223428408-ac6c9f9a-51bb-4404-a021-588eff9efe40.png)
